CFLAGS=-Wall -pipe -ansi -D_GNU_SOURCE

all: idxset.o queue.o strbuf.o mainloop.o iochannel.o packet.o \
	memblock.o sample.o socket-server.o memblockq.o client.o \
	core.o main.o outputstream.o inputstream.o source.o sink.o \
	pstream.o protocol-simple.o protocol-simple-tcp.o sink-pipe.o \
	module.o

clean:
	rm -f *.o
